---
title: 'NYC Planning Labs: Modern GovTech'
timezone: UTC
collections:
  about:
    title: About
    output: true
    permalink: "/:path/"
  authors:
    title: Authors
    output: true
    permalink: "/author/:name/"
  contact:
    title: Contact
    output: false
    permalink: "/contact/:path/"
  join:
    title: Join
    output: true
    permalink: "/join/:path/"
  posts:
    title: Posts
    output: true
  press:
    title: Press
    output: true
    permalink: "/press/:name/"
  projects:
    title: Projects
    output: true
    permalink: "/what-we-deliver/:path/"
  styleguide:
    title: Styleguide
    output: true
    permalink: "/styleguide/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
- scope:
    path: pages
  values:
    layout: primary
- scope:
    path: _authors
  values:
    layout: default-profile
- scope:
    path: _contact
  values:
    layout: primary
    subnav_anchor: "/contact/"
- scope:
    path: _about
  values:
    layout: primary
    include_subnav: true
    subnav_anchor: "/about/"
- scope:
    path: _projects
  values:
    layout: project-page
- scope:
    path: _styleguide
  values:
    layout: styleguide
    include_subnav: true
description: NYC Planning Labs builds open, impactful technology tools for NYC's Urban
  Planners.
baseurl: 
permalink: pretty
url: https://planninglabs.nyc
localhost: localhost:4000
env: production
logo: 
tag_dir: tags
github_repo: https://github.com/NYCPlanning/labs-planninglabs.nyc/blob/master
future: true
related_posts: 3
google_analytics: UA-84250233-4
analytics:
  google:
    code: 
  dap:
    agency: DCP
    subagency: Labs
paginate: 5
paginate_path: blog/page/:num
jekyll-archives:
  enabled:
  - tags
  layout: tag-results
  permalinks:
    tag: "/tags/:name/"
frontmatter_tests:
  path: tests/schema
footer:
  image: 
  email: 
  twitter:
  - nycplanninglabs
  text: This site was cloned from 18F.gsa.gov</a>.
markdown: kramdown
highlighter: rouge
exclude:
- ".about.yml"
- ".cfignore"
- ".codeclimate.yml"
- ".gitignore"
- ".gitmodules"
- ".hound.yml"
- 404.html
- api-endpoints
- bin
- build
- circle.yml
- config_blog.rb
- CONTRIBUTING.md
- docker-compose.yml
- docker_entrypoint.rb
- Dockerfile
- examples/
- Gemfile*
- ISSUE_TEMPLATE.md
- killport
- LICENSE.md
- node_modules
- package.json
- pages/our-work.html
- PULL_REQUEST_TEMPLATE.md
- README.md
- spec/
- system-security-plan.yml
- tests/
- tests/schema/tags.yml
- tmp/
- vendor
gems:
- jekyll-sitemap
- jekyll-archives
- jekyll-redirect-from
- jekyll-feed
- jekyll-seo-tag
- jekyll-paginate
jekyll_pages_api_search:
  index_fields:
    title:
      boost: 10
    tags:
      boost: 10
    url:
      boost: 5
    body: 
